### PR TITLE
UC Davis EEC 289Q

### PR DESCRIPTION
**Pull request by behoppe**
Updated teaching-performance page with a new major entry for EEC 289Q, with links to PDFs on Box.

On the same page, also added links from the Modern Algorithms Workshop to PDFs, which are also on Box.

FYI, I configured the PDF links to allow viewing but not downloading, with the intent of encouraging people to contact us for additional access. I don't feel strongly about preventing downloads of PDFs, but wanted to mention this setting here.

### CODE REVIEW

**Comment by behoppe** [comment]
Hi @neboat @jowens @DorothyCurtis -- this PR adds John's EEC 289Q course to the "Teach performance" page, and it fleshes out the Modern Algorithms Workshop section (which was nominally already part of the page) with links to PDFs of all the lectures. Could you please give your blessing to proceed with publishing course materials this way? Thank you.

FYI this page is deliberately terse about EEC 289Q because there is an entire blog post about that class in our publication pipeline. When that blog post gets published, then I'll update this page to cross-link with that blog post.

**Comment by jowens** [comment]
I'm fine with this, but are the Box links actually public? (Are my PDFs publicly linkable?)

**Comment by behoppe** [comment]
Thanks @jowens. Yes, there is a "Share" button for each file on Box, and right now I made the PDFs publicly viewable but not downloadable. Those links are what's on the updated webpage. Is that OK? I know the Box folder is in general a private space. I tried to work with the data "in its native location" without making additional copies. Another alternative could be splitting public files into a public folder (either Box or GitHub).

**Comment by neboat** [comment]
FYI, on my end, I tried accessing one of the PDFs from an incognito window, and it succeeded.  From that window, I didn't see an obvious way to access anything else in the Box, so the rest of the Box seems to still remain private.

**Comment by behoppe** [comment]
Thanks @jowens and @neboat for the reviews. I have rebased and merged.

**Pull request merged**
