### PR TITLE
Revamped Join us form

### PR DESCRIPTION
**Pull request by behoppe**
Testing netlify form

### CODE REVIEW

**Comment by behoppe** [comment]
@syhlalala this PR has the new revamped Join us form, based on the HOPC survey. You can go directly to the new form at https://deploy-preview-228--sage-licorice-6da44d.netlify.app/community/join-us/. Please take a look and let me know if you think it's ready to go on the production site. Thanks!

**Comment by syhlalala** [comment]
> @syhlalala this PR has the new revamped Join us form, based on the HOPC survey. You can go directly to the new form at https://deploy-preview-228--sage-licorice-6da44d.netlify.app/community/join-us/. Please take a look and let me know if you think it's ready to go on the production site. Thanks!

Hi Bruce,

Thank you for adding the survey! I have a few minor comments:

- In the first paragraph, maybe we should mention "research" somewhere since this survey is mainly about research activities. One possibility is to change "This survey invites you to become part of Fastcode and help guide next steps for the community" to "This survey invites you to become part of Fastcode and help guide next steps for the *research* community." 

- For the question "Considering your areas of interest, which conferences do you think represent the best SPE research? You may optionally include rankings and/or comments with your answer." Maybe we can remove "rankings" since it's a bit vague to define the rank. Maybe we can say "rank them based on your preference"?

- In "Which activities would be most interesting to you for SPE community-building?", we should remove "like HOPC" from the first option. 

- I would also prefer adding a number label for each question. We can label them from "Please describe your research area and research interests." Then in the email we can say "you only need to answer 8 simple questions."  (We can even remove one or two questions to make it shorter, but I'm not sure. What do you think?)

Other than that, it looks great to me in general. Thanks again for integrating this into the website!

Best,
Yihan

**Comment by behoppe** [comment]
Thanks @syhlalala. I addressed all your concerns with my recent updates. Rather than adding more language about research, I made the whole survey more general by saying things like
> Please describe your work interests (e.g., research) related to SPE.

I also changed the page title from "Join us" to "Join Fastcode" -- which required that I change the navbar/header options the site to say "Blog" instead of "Fast code".
Screenshot 2024-07-16 at 14-23-58 Join Fastcode

 All of the "fastcode" references are going to be sort of fluid as we get fastcode.org running, but, in any case, I think the whole site benefits from these changes. What do you think?

**Comment by behoppe** [comment]
@syhlalala I would like to merge this updated Join-Us PR tomorrow. Please let me know if you have any concerns. Thank you :-)

**Pull request merged**
