### PR TITLE
Update contribute.md

### PR DESCRIPTION
**Pull request by neboat**
Starting a list of open projects for prospective OpenCilk contributors.

Please feel free to suggest other projects to add to this list.

### CODE REVIEW

**Comment by neboat** [comment]
I'm totally fine with reorganizing.  Primarily, I wanted to open this PR to put some stake in the ground for listing specific programming projects that people might take on.  (If I recall correctly, Vivek originally suggested creating such a list many years ago, and I feel we're long past due to take up his suggestion.)

I'm fine with changing the header.  I borrowed "Open projects" from LLVM's website: https://llvm.org/OpenProjects.html.  But I suspect that LLVM primarily caters to code contributions are the primary way for external contributors to contribute.  In contrast, I suspect we want to support a broader variety of contributions to the OpenCilk ecosystem, including teaching materials and written materials related to software performance engineering.

I would like to make this list of coding projects prominent and easy to find on the website.  I've started to get more direct communications from third parties asking about possible coding projects they might take on to engage with the OpenCilk software.  So I think it's important to make this list easy for visitors to quickly find this list.

To this end, I could imagine keeping this content at the top-level of the section hierarchy on the page.  We could combine this list with the existing "Coding" section, or replace that section entirely, since I see that existing content as more documentation of the source-code organization than contribution opportunity.

Alternatively, I could imagine creating a new page dedicated to these coding projects.  A separate page would make it more natural to provide longer blurbs describing the project, including experience needed, who to contact, etc.  (See, for example, [LLVM's page on open projects](https://llvm.org/OpenProjects.html).)  The existing format as a list on the existing page makes it awkward to say much about each project.  What do you think about adding a new page focused on open programming projects?

**Comment by behoppe** [comment]
Thanks @neboat. Yes, I see what you mean about LLVM and OpenCilk, and I like the idea of a separate page for open projects. I will try that out and hopefully push something to this PR soon for consideration.

**Comment by behoppe** [comment]
@neboat I made a standalone page for open projects for your consideration. While re-organizing contribute.md, I wanted the "Teaching" item to stand out. I experimented with ```{% alert %}``` and several image/layout combinations and ended up with the owl floating left of the text. I realize this may be an "improper" use of "owl" but I like the look, so I hope we can find a way to give "Teaching" a bit of emphasis, perhaps with this very owl image.

**Comment by behoppe** [comment]
@neboat I am merging this and I welcome future edits. Thanks for these open projects.

**Comment by neboat** [comment]
Thanks, @behoppe, and sorry for dropping the ball on this.  I can imagine some further revisions, but this seems like a good first step.

**Pull request merged**
