### PR TITLE
prototype with pydata-sphinx-theme

### PR DESCRIPTION
**Pull request by behoppe**
Use a complete sphinx site in src/sphinx to deploy pydata-sphinx-theme, which has been pulled into the 11ty site styling and templates.

### CODE REVIEW

**Comment by behoppe** [comment]
Hi @neboat @DorothyCurtis @ailiop @cleiserson, this PR presents a revamped user interface based on the [pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/) used by Pandas, Numpy.org, etc. I am advancing this theme instead of the sphinx-bootstrap-theme because the pydata community is extremely active in developing this theme, whereas the sphinx-bootstrap-theme is dormant and relies on lots of deprecated technology.

With this draft, we have a superficial appearance very similar to the existing site, and the overall Eleventy architecture of markdown files is unchanged. But all the underlying templates (and CSS and JS) are completely replaced by content generated by Sphinx + pydata-sphinx-theme.

I think this is ready for a test-drive and I would appreciate your comments. Please bear in mind that the home page still needs work, as do the "fancy landing pages" in general (e.g. blog landing, doc landing). What does work now are the basic article pages. You will see

- Fixed navbar that does not hide content
- Much better scrolling properties, including two fixed sidebars
- Horizontal scrolling of code blocks.

For example, see the [Cilkscale users guide](https://deploy-preview-186--sage-licorice-6da44d.netlify.app/doc/users-guide/cilkscale/) and the [glossary](https://deploy-preview-186--sage-licorice-6da44d.netlify.app/doc/reference/glossary/). I look forward to hearing your impressions of the new UI.

**Comment by behoppe** [comment]
Thanks @neboat @timkaler @ailiop @DorothyCurtis for Friday feedback on the revamped theme. This update implements some key things we discussed, most notably a single responsive sidebar and much wider body. It also has refinements to anchor and defn links.

The "fancy landing pages" still need work. Also, the word-wrapping of individual navbar items is not fixed, but I observed that the exact same behavior occurs on the current site, so I'm holding this an overall issue and not one specific to this PR.

There was a lot of discussion Friday about page width and sidebar behavior, and I think this achieves what we wanted in terms of helping users to scan, read, and navigate. Please take a look and let me know, thank you.

**Comment by behoppe** [comment]
Hi @ailiop @neboat @timkaler @DorothyCurtis @cleiserson I have implemented the "fancy landing pages" and made other improvements to the revamped website theme. I think it's very close to ready for publication on the main branch. Can you please take a look? Thank you.

To see the difference, I recommend trying pages like the Cilkscale documentation and glossary, where many of the improvements should be evident when you compare this with the current theme.

**Comment by neboat** [comment]
Hey @behoppe, I really like the improvements you've made!  There are some other improvements I could suggest, but I don't think they're blockers, and I don't want them to slow down deploying these changes.

A couple minor comments:
- I'm finding that, every time I come back to the website after working on other things for a while, I've forgotten that the "Fast code" label refers to our collection of blogs and announcements.  I think it would help it have a more descriptive label here.
- The font size for code is a bit large on my system.  For example, see the code next to the paragraph text in this screenshot:
Screenshot 2023-03-08 at 6 59 29 AM

**Comment by behoppe** [comment]
Thanks, @neboat! I take your feedback as a green light for merging :-)

I appreciate your comments and will work on them. Can you please remind me about your OS/browser? Below is what the fonts look like for me. I had to do some manual balancing of font sizes to make it look this way, and I'm guessing that my manual adjustments somehow aren't working on your system. I also see that your code-block divs are getting the "wrong" monospace font (which should match the orange inline code).
Screenshot 2023-03-08 at 14-41-31 Cilkscale — scalability analysis   benchmarking tool

**Comment by neboat** [comment]
I'm looking at the page using Chrome on a system running macOS 13.

This morning I also noticed an issue with colors — especially the font color of the main text — when viewing the website on the same browser and OS in dark mode.  This color issue might be a blocker for accepting the changes, but hopefully it's easy to resolve.  You can see the issue in this screenshot:
Screenshot 2023-03-09 at 6 29 07 AM

**Comment by behoppe** [comment]
Thanks @neboat. Yes I would say the dark mode behavior is unacceptable. The underlying pydata-sphinx theme supports light and dark modes, and I had attempted to simplify my job by suppressing dark mode, but evidently it's still happening in some form. So I'll either "close the leak" in my existing approach, or I will bite the bullet and build in support for dark mode, all the way through the web-code stack.

**Comment by behoppe** [comment]
Hi @neboat the theme now supports dark mode, and I configured colors from our palette that I think work OK. @ailiop I am pretty sure your a fan of dark mode, and I am also curious what you think.

The latest changes essentially removed "my styling" where it was obstructing "pydata-sphinx" styling, so that the core pydata-sphinx parameters work more like they're supposed to. One especially notable change is the alert box, which previously triggered Bootstrap alert boxes, but now triggers pydata-sphinx "admonition boxes" (which -- you guessed it -- ultimately trigger Bootstrap alert boxes). The new alert boxes look more sophisticated IMO, and are certainly more adaptable for light/dark themes.

The text size issue remains open, but I think we agreed that's non-blocking. Hopefully we agree this is ready to go!

**Comment by ailiop** [comment]
@behoppe This is really coming together, I like it!

I am perusing the revamped website design and trying to pay special attention
to the new (and much appreciated) dark mode.  I have collected a bunch of
comments below.  This is a very long post, I hope you find it helpful, not
tedious.  :)

Regarding the dark theme, I am looking at the following comparison:

1. "Native" dark webpage theme (i.e., the new option that you enabled), vs
2. Light webpage theme + dark mode via my browser extension ([dark
   reader](https://darkreader.org/)).
   
You can see screenshots comparing (1) and (2) below.  Note that I'm using
different browsers (Edge for 1, Thunderbird for 2).  This is mainly for my own
convenience (the dark reader extension applies globally, not per webpage), but
I verified that the native dark theme colors look the same in both browsers.
You may notice some other differences such as teletype font size, rounded
corners in images, etc.

OK, that's enough preamble.  Below are my comments, organized by example page.
Some were already brought up by @neboat, but I repeat them here for
completeness.

### Landing page and feature blog post boxes

| Native dark theme (Edge)       | Native light theme + dark mode extension (Firefox) |
|:------------------------------:|:--------------------------------------------------:|
| native-landing-background | extension-landing-background |
| native-landing-post-background | extension-landing-post-background |
| native-landing-post-text | extension-landing-post-text |

You can see an extra little window with a 6-digit hex value in each screenshot.
These show the rendered color for the following element (from top to bottom):
page background, blog-post box background, blog-post box text.

- **"Silk" background:** Needless to say, this looks much better with the
  native dark theme.
- **Section titles:** In the light+extension screenshots, section titles are
  colored light blue, in similar style to the light mode.  E.g., "write fast
  code with C/C++ and OpenCilk", "Featured blog posts", "OpenCilk 2.0
  released".  In the native theme, titles are colored the same as regular text,
  which make them stand out less.
- **Text contrast:** The relative background-foreground tones in the
  light+extension screenshots are much more pleasing to my eyes.  By
  comparison, the native dark theme has higher contrast (see the color hex
  values), which I find to be a little "harsh", especially with the true-black
  background.
- **Links:** There is a color-palette inconsistency between the native light
  and dark themes.  In the light theme, links are colored the same as titles;
  in the dark theme, links are colored the same as bullet points.  (See the
  color of the "NEWS" and "RELEASE" tags or the underline in "OpenCilk 2.0
  released".)

### Footer

| Native dark theme (Edge) | Native light theme + dark mode extension (Firefox) |
|:------------------------:|:--------------------------------------------------:|
| native-footer | extension-footer |

- **Contrast:** Opposite to the "main" text, contrast is a bit too low with the
  native dark theme.  The dark mode extension, on the other hand, is a bit too
  high-contrast.  Something in between would be great, in my opinion.
  
### Install page

| Native dark theme (Edge) | Native light theme + dark mode extension (Firefox) |
|:------------------------:|:--------------------------------------------------:|
| native-install | extension-install |

- **Code boxes**: This is number one deficiency of the native dark theme in its
  present state, in my opinion.  Although the brownish code-box background in
  the light+extension screenshot does not find the overall color scheme well,
  it is pleasantly dark and all elements of the color-highlighted code are very
  easy to read.
- **Links:** I prefer the right-hand side styling where the links have
  different colors than the bullet-point triangles.  The left-hand screenshot
  almost gives me the impression that the triangle is part of the link.
- **Navigation pane (left):** The navigation pane looks way better with the
  native dark theme.  I do observe a minor downside, however: the bolded
  elements (active page & section) do not stand out enough.  Somehow, to my
  eyes, it is easier to notice the bold styling with the colored text than with
  the white text.
- **Navigation bar (top):** I think keeping the same dark-blue background color
  that is used in the light theme is fine.  I am tempted to make some argument
  about consistent branding here, but I'm not sure I feel that strongly about
  it.
- **Search box (top right):** I much prefer the dark search-box in the
  right-hand screenshot.  In general, I find large light-colored elements to
  create unnecessary eye strain.  They cannot always be avoided, but I thought
  I'd voice my preference.  :)
  
### Cilkscale reference page

| Native dark theme (Edge)  | Native light theme + dark mode extension (Firefox) |
|:-------------------------:|:--------------------------------------------------:|
| native-cilkscale-terminal | extension-cilkscale-terminal |
| extension-cilkscale-plot | native-cilkscale-plot |

- **Terminal output:** The lines enclosed by `>> ... <<` are barely visible.  I
  think you had previously resolved this issue separately in the light theme.
- **Plots:** I accept that the plots will probably have to be light and I think
  that's OK.  For some reason, however, they are made noticeably dimmer with
  the native dark theme.  This is not an illusion due to the different
  background — see the color hex values.  (The color is the same in Firefox
  with the native dark theme.)
  
Finally, here's two comments that are unrelated to the light/dark theme.  Both
pertain to the side navigation pane on the left.

- The section "C/C++ API for fine-grained analysis" is never highlighted when I
  am reading through it.
- In the Firefox (right-hand side) screenshot, the last section is broken
  across two lines as "Benchmarking and visualization \\ Python script".  Since
  "Python" is capitalized, this creates the illusion that there's two sections
  there: a "Benchmarking and visualization" section and a "Python script"
  section.  I think it'd be helpful to either add some element like a bullet
  point in front of each section, or to have noticeably more vertical space
  between section titles than within lines belonging to the same section title.

**Comment by behoppe** [comment]
Thanks @ailiop for your detailed and constructive feedback. I look forward to improving the dark theme based on these comments. Would you be OK if I fixed dark mode after merging the existing improvements into main? I am eager to share the improved UI, and not sure how long it will take to address your comments.

**Comment by behoppe** [comment]
Thanks @ailiop.

@neboat I think the only potentially blocking thing here is Disqus dark mode, as you noticed. Do you think that is actually blocking?

I am working on a Disqus fix, and it may take some time. [Here it explains that](https://help.disqus.com/en/articles/1717201-disqus-appearance-customizations) Disqus automatically detects light vs dark mode, but for some reason that feature is not working for us. It also explains how to customize the styling, but everything seems embedded inside javascript-generated CSS, and I'm finding it tough sledding to follow along so far.

**Comment by behoppe** [comment]
I was able to adjust the background color of the Disqus comment section and make it readable in light and dark modes. So I merged the new theme into the main branch. Yeah! Thanks @neboat and @ailiop for your feedback and encouragement.

**Pull request merged**
