### PR TITLE
Update teach performance.md

### PR DESCRIPTION
**Pull request by jowens**
#9 some starting material, seed for discussion on what should be on this page

### CODE REVIEW

**Comment by behoppe** [comment]
Thanks, @jowens, for this contribution.

**Comment by jowens** [comment]
I figured we'd talk about it before merging, but glad you like it!

**Comment by behoppe** [comment]
Thanks for that extra context. I am still discovering our team workflow, and treating the website as openly in-development. After building it solo for weeks, I'm excited to have new contributors. Next time you contribute something, I won't be so easy on you 🙂
________________________________

**Comment by jowens** [comment]
I figure if I want to incorporate changes, doing it as a pull request (so someone's eyes can look at it, and edit it if necessary) is sensible. Pull request == staging area. But you're the boss on how you want to manage changes.

**Pull request merged**
