### PR TITLE
implement TB and team glossary feedback

### PR DESCRIPTION
**Pull request by behoppe**

### CODE REVIEW

**Comment by behoppe** [comment]
@ailiop I wonder if you could please help me to untangle this github mess that I made? After putting my edits into 66f08de1a234a3b116685b6ee6b89e0562678fb3 and 85d066bd062eee33dca78898b9a6b585a60b10a9, I thought I was merging into main, but it seems that I did the opposite and merged main into this branch? I am not sure what to do next -- want to merge my edits into main. Sorry about this.

**Comment by ailiop** [comment]
@behoppe If I understand what's happened correctly, you should be able to undo the unintended merge and then merge the right way:

1. Make sure the your local repo is on the PR branch.  
    - The following will make some destructive changes to the branch; if you are worried about losing work, make a backup branch (starting at `behoppe/behoppe-cilkplus-glossary`) and switch back to the PR branch.
2. Hard-reset the PR branch to commit [85d066b](https://github.com/OpenCilk/www.opencilk.org/pull/176/commits/85d066bd062eee33dca78898b9a6b585a60b10a9) (i.e., just before the "bad" merge).
    `git reset --hard 85d066b`
3. Force-push to the PR branch remote, effectively undoing the "bad" merge commit.  E.g., if your remote is named `behoppe`:
    `git push --force-with-lease behoppe behoppe-cilkplus-glossary`
4. Merge the PR as you normally would.

**Comment by behoppe** [comment]
Thanks @ailiop, your advice helped me a lot. I started using GitHub Desktop along the way, and needed to resolve a bewildering number of conflicts -- mostly related to infrastructure changes (for `defn` and `sphinx-bootstrap-theme`) that got a bit mixed up into this glossary stuff. I hope those conflicts don't ripple into confusion for other PRs.

**Comment by behoppe** [comment]
Hi @ailiop unfortunately my PR included 9ea46115debbb791e9509442c90d077eda3443c0, which removed a whole slew of great new articles from publication on the main branch. Sorry. I am not sure where exactly I goofed or how to repair this. (I guess that there was a moment when I needed to update my PR branch and the change went in the opposite direction.) Thoughts? I am sorry for all the trouble.

**Comment by ailiop** [comment]
@behoppe If removing the [9ea4611](https://github.com/OpenCilk/www.opencilk.org/pull/176/commits/9ea46115debbb791e9509442c90d077eda3443c0) commit would fix the issue, you can accomplish that with an interactive rebase of the PR branch onto some earlier commit and _drop_ the offending commit in the rebase.  You would have to force-push the rebased branch.

As before, since force-pushing is destructive, you may want to first make a local copy of the branch before the above.

**Comment by behoppe** [comment]
Hi @ailiop thank you very much. I think I did not follow your advice correctly the first time. sorry. This time around I took more care to use rebase --interactive and the result is #179. Unfortunately, when I merge that into main the result is still missing all the articles that I accidentally removed. However, I see in the deploy preview for #179 that those articles are published in that branch. I am confused about this and will follow up with you. thanks for your help and advice!

**Pull request merged**
