### PR TITLE
Create Tutorials “introduction-to-cilk-programming”

### PR DESCRIPTION
**Pull request by behoppe**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by behoppe** [comment]
@cleiserson and @ailiop, would either/both of you be willing to please review my new tutorial, "Introduction to Cilk programming"? 

You will see that I opted for a short first tutorial -- which aims to introduce `cilk_spawn` and `cilk_scope` purely in terms of semantics, without getting into performance analysis or any other keywords (`cilk_for`, `cilk_sync`).

You can disregard the current featured image (trace-dag) for now. I will make a new featured image that shows some code in full-color close-up (as you see now on the site home page).

Thanks for considering this!

**Comment by DorothyCurtis** [comment]
hello this is a comment from Dorothy

**Comment by behoppe** [comment]
Some comments from @cleiserson 
- focus on runtime, not storage, energy
- be careful about "exceedingly complicated"
- task-parallelism is about logical tasks
-  int declarations are ok with cilk_sync but can't happen inside cilk_scope

**Comment by DorothyCurtis** [comment]
Thanks, Alex, for the update!

Dorothy

**Comment by behoppe** [comment]
Thanks, @ailiop. I am going to make a few edits right now (this afternoon) and then turn it over to you for review.

**Comment by behoppe** [comment]
OK my edits are done. I tried to address comments from yesterday's meeting, and I also took a stab at tips on using "receiver variables." These tips are not part of the *Intro to Algs* primary source, and I don't have another good formal source, so I may be technically sloppy, but I think it's helpful to ground Cilk programming with these sorts of examples and tips. My $0.02.

Thanks @ailiop for reviewing.

**Comment by ailiop** [comment]
@behoppe I just finished a pass over the tutorial.  I was finding it difficult to make some of the comments I had in mind using GitHub's code review interface, so in the end I decided to simply attempt and commit a partial rewrite.  This may make it difficult to pick and choose subsets of my suggested (i.e., committed) edits.  If you feel parts (or the entirety) of my commit need to be reverted, I am happy to help make that happen.

Here is a summary of the changes in my commit, apart from editing or rewriting paragraph text:

1. Discuss `cilk_scope` together with `cilk_spawn`
    - I introduced the notion of a "parallel region" to (hopefully) make the spawn/sync discussion clearer
2. Some section restructuring:
    - Move the introductory paragraphs outside of the `cilk_scope` & `cilk_spawn` example section
    - Attempt to add some relevant content in the "How OpenCilk runs your program" section
    - Group the danger/success examples into a "Common pitfalls and how to avoid them" section
3. Mention some additional `defn` keywords:
    - sync, nested parallelism, logical parallelism, continuation
4. Minor restructuring of the example `p_fib()` & `fib()` codes
    - Note that this means you'd have to regenerate the figure in the tutorial.  Sorry.
6. I added a note about being able to `cilk_spawn` a block statement

And here are some additional higher-level comments:

**(1)** One downside of my edits is that they made the tutorial longer.  I decided to not pare it down more aggressively before you got a chance to review the edits.  My current thoughts on what could be cut down are:

- The "How OpenCilk runs your program" section could be replaced by a link to a documentation page or blog post that talks about just that.  The only point which I think is useful for this tutorial is that the programmer is responsible for expressing *logical parallelism* and the runtime takes care of the rest (maybe also mention that it guarantees near-optimal scheduling/load-balancing).

- The discussion of two forms of a `cilk_spawn` for `void` vs non-`void` functions feels somewhat distracting.  It makes certain technical sense (and could perhaps be useful in contrasting Cilk to other parallel platforms) — but here it may be better to try to emphasize simply that spawning a function is syntactically analogous to calling it.  The notion of a "receiver variable" might still be useful for the pitfall example where the value `x` is indeterminate.

- The example of `cilk_spawn`ing a non-function block can probably be removed as-is.

**(2)** While I totally agree with the goal of keeping these tutorials succinct and focused, I am conflicted about leaving `cilk_for` out of Part 1.  The reason is that I suspect the majority of people who want take a first stab at parallelizing something probably start by trying to parallelize a `for` loop.  If you agree with that, I am thinking of two possible ways to address that concern:

- Add a very short section with a trivial example of a `cilk_for` (e.g., summing two vectors) and a link to the eventual part 2 of the tutorial for more details.
- Add "subtitles" to these tutorials, e.g., "Introduction to Cilk programming, part 1: spawns and parallel recursion", "Introduction to Cilk programming, part 2: parallel loops", etc.  I don't think these are necessarily good titles, but the idea is to make it easy for someone who sees a list of the tutorials to know in advance what to expect in each one.

I hope all this makes sense.  :)

**Comment by behoppe** [comment]
Thank you, @ailiop, for your edits. I think the tutorial is much improved. I think the team will be reviewing this tutorial as part of today's meeting. (Right, @DorothyCurtis?) I am going to update the figure right now, and I look forward to sharing this tutorial with the team for their feedback.

**Comment by behoppe** [comment]
@ailiop I propose to publish this tutorial (merge with the main branch). Is that OK with you?

I know we are likely to change it as we develop the introduction to `cilk_for` #141, but I think it's worth publishing as a replacement for the ["OpenCilk keywords" tutorial](https://www.opencilk.org/doc/tutorials/keywords/).

**Comment by ailiop** [comment]
@behoppe I think your proposal is good.  I would like to raise a couple of caveats from my point of view.

1. The existing page may need a few quick edits.  Mainly, I would take off the "How OpenCilk runs your program" section altogether.  Part of its content has already been moved to the 2nd paragraph of the introductory section, and in its current form it provides little information.
    - I do like the updated graphic, particularly the "OpenCilk arrow", but I just think it belongs to a page which actually covers how OpenCilk runs a parallel program.
2. I think there may still be value in something like an "OpenCilk keywords" page, although not quite a tutorial.  I am imagining a page which lists all 5 keywords (`cilk_for`, `cilk_spawn`, `cilk_scope`, `cilk_sync`, `cilk_reducer`) together with a terse code-snippet example and a link to a tutorial/reference with more information.  Basically, a kind of beginner's cheat sheet in page form.  
3. Maybe we could add a very basic computation-trace figure to illustrate the notion of (nested) task-parallelism with spawns and syncs to accompany the text about _parallel regions_.
4. We may also want to change the title.  "Part 1" is nondescript.  Maybe add a subtitle, e.g., "Introduction to Cilk programming, part 1: parallel tasks" (or "... nested task-parallelism", or something better)?

We do not necessarily need to fix everything to publish the tutorial, of course.  I defer to you on that decision, but I will make a quick pass right now to address point (1).

**Comment by behoppe** [comment]
Thanks @ailiop. I like your edits. I changed the title to "Introduction to Cilk programming 1: parallel tasks", and I also edited the headers. Finally, I put the image back in -- right after the paragraph that's about how OpenCilk runs your program. I think it's important to have a good image with this article, and IMO this one fits the bill. If you think a different image would be more appropriate, I am happy to work on that.

I am going to merge with main. Big moment!

**Comment by behoppe** [comment]
@ailiop actually I need help to merge this. There was a conflict with `/img/fib-code-multicore.png` (an image that does not even appear in the tutorial, but which got into this branch because I goofed some time ago). I wasn't sure about using the command line, and so I committed the very latest `/img/fib-code-multicore.png` to this branch, but I think that just made the conflict worse. I fear that whatever I do next will really mess up the repo. Can you please help?

**Comment by ailiop** [comment]
Let me try a rebase.

**Comment by behoppe** [comment]
wait I am in the middle of something

________________________________

**Comment by behoppe** [comment]
@ailiop I have merged this PR with the main branch on my local repo. Do I just push that to this repo now?

**Comment by ailiop** [comment]
Alright, it appears that the rebasing is done and the conflict is resolved!

For posterity, this entailed the following steps:

#### 1. Find the offending commit(s)
 
In this case, we could do that by filtering the git log of this PR branch to show only those commits that touched the conflicting image file.  For example, in my local clone of the repo where I have checked out the `cms/tutorials/introduction-to-cilk-programming` branch that tracks this PR, I can run the following:
```sh
git log -- src/img/fib-code-multicore.png
```
Thankfully, this only yielded a handful of commits.

#### 2. Understand the conflict.
 
There were 3 commits in this PR that related to the conflict.

1. One commit deleted the image file in question.
2. The next one added the image file again.
3. The last commit in the PR modified the image file (to match that in `main`).

It seems like the error was deleting the image file from the branch as part of commit (1).  This was then compounded by trying to fix the error with commits (2) and (3).  The image was part of the `main` branch; moreover, it was being modified throughout the history of the `main` branch.

So, the desired effect would be to make it as if the offending commits never happened, right?

Well, almost.  It turned out that commit (1) included some changes to the text in addition to the image deletion.  What we want then, is to keep *that part* of commit (1) and remove commits (2) and (3) altogether.

#### 3. Rebase (make it happen)

We want to rebase our currently checked-out branch (`cms/tutorials/introduction-to-cilk-programming`) onto `origin/main`.  We can do that interactively with:

```sh
git rebase -i origin/main
```

This opens up a text editor with a manifest of all commits in our PR branch and the command `pick` for all of them.  We make the following changes:

- Add a `break` command before the line where commit (1) is picked.
- Change the command for commits (2) and (3) into `drop`.

Save, exit, and continue the rebase.

When it reaches the `break` command, it will stop and present us with the staged changes of commit (1).  We unstage the undesired deletion of the image and continue the rebase.

...and, fiinally, that's it.  We can now force-push our local, rebased and conflict-free branch of the PR to the remote branch of the PR.

### Some parting thoughts

1. I think this was more complicated than it could have been due a combination of two reasons: (i) the conflicting file was an image rather than text; and (ii) the conflict involved the file getting deleted, not just edited.
2. In this case, the easiest fix when the image was accidentally deleted would probably have been to: (i) reset the branch to the commit prior to the offending one; (ii) make a new commit which includes the intended changes but not the unintended deletion of the image; and (iii) force-push the change to the remote branch of the PR.

**Comment by behoppe** [comment]
Thank you @ailiop!!

**Pull request merged**
