### PR TITLE
cilkc in prismjs for intro to cilk programming

### PR DESCRIPTION
**Pull request by behoppe**
new prism.css with theme for parallel-keywords;
use cilkc in intro to cilk programming;
update fib-code image in the intro.

### CODE REVIEW

**Comment by behoppe** [comment]
@ailiop you can see `cilkc` with the deploy preview for this PR. (Ignore "All checks have failed" because I fixed it on Netlify.) I also fiddled with the theme to use our color palette a bit more, and tried the tangelo for parallel-keywords. Thanks for making this possible.

**Comment by ailiop** [comment]
@behoppe Thank you, the Cilk keywords look great!  I think the rest of the theme may need some more tweaking, mainly because the contrast between the lime-green function tokens and the gray background is a bit too low for my eyes.  (Interestingly, the code looks great when I apply my browser-extension dark mode filter.)

Possible improvements:
- Use "blue" for keywords and built-in types.
- Use "teal" for functions.
- Maybe use different colors for keywords and built-in types, possibly adding "lime" or "americanyellow" to the mix.

**Comment by behoppe** [comment]
@ailiop I made several adjustments which improve foreground-background contrast and character-color balance:
- Blue keywords
- Shift the blue a bit lighter
- Shift the lime and the tangelo a bit darker
- Shift the background a bit lighter.

I personally like green for functions, if that works, because green on the website associates with clicking links, which I think has a similar notion as a function call. What do you think?

You can easily see the previous theme represented by the image in this intro article btw.

**Comment by ailiop** [comment]
@behoppe Thank you, this looks much better to my eyes!

I think there may still be some benefit to differentiating between keywords (`if`, `return`, etc) and built-in types (`int`, etc), perhaps by using different shades of blue.

And the image at the top of the _Introduction to Cilk programming_ tutorial should be updated once the style is finalized.

**Comment by behoppe** [comment]
Thanks @ailiop. How do I differentiate `return` from `int` with prismjs? I could not find a CSS class that distinguished them, and I'm actually convinced there is no distinction in prismjs. (But I could be wrong.)

**Pull request merged**
